[theme]
primaryColor = "#800020"
backgroundColor = "#FAF4F6"
secondaryBackgroundColor = "#F5E6E9"
textColor = "#331118"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
