[theme]
primaryColor = "#800020"
backgroundColor = "#FAF4F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2D0A11"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
